### ISSUE TITLE
build with non-standard location of zlib/boost/gsl

### ISSUE THREAD

**Issue by orionzhou** [bschiffthaler/seidr#1]
I tried to follow the instruction document to build seidr:

> cmake -DCMAKE_BUILD_TYPE=Release ..

but it seems to find system libraries which are old:

> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
> -- Boost version: 1.53.0

I tried to use:

> cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/seidr ..
> -DZLIB_INCLUDE_DIRS=~/miniconda3/include -DZLIB_LIBRARIES=~/miniconda3/lib  ..

but it does not seem to work - so how can I tell cmake to use my custom locations of zlib/boost/GSL libraries?

Thanks!

**Comment by orionzhou** [comment]
Okay,  so after setting the CMAKE_PREFIX_PATH I was able to get it compiling, till this error occurs:

> (base) zhoux379@ln0004:build $ make
> [  5%] Built target seidr-common
> [  8%] Built target pcor
> [ 10%] Built target plsnet
> [ 13%] Built target mi
> [ 21%] Built target ranger
> [ 24%] Built target genie3
> [ 26%] Built target seidr-glmnet
> [ 29%] Built target el-ensemble
> [ 31%] Built target anoverence
> [ 35%] Built target tigress
> [ 38%] Built target bs
> [ 66%] Built target networkit
> [ 67%] Linking CXX executable seidr
> /panfs/roc/groups/15/springer/zhoux379/software/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: CMakeFiles/sei
> dr.dir/src/Seidr/adjacency.cpp.o: in function `adjacency(int, char**)':
> adjacency.cpp:(.text+0x1f50): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'

I tried set LD_LIBRARY_PATH:

> (base) zhoux379@ln0004:build $ export LD_LIBRARY_PATH=/springer/zhoux379/software/miniconda3/lib

but the error still comes out, any idea? Thanks for your time and patience!

**Comment by bschiffthaler** [comment]
Are you sure it's linking now against a recent version of boost? Can you purge the build dir and post the entire log including the cmake configuration?

**Comment by orionzhou** [comment]
Ok I deleted everything and build it from scratch, 

here is the [building log](https://github.com/orionzhou/orionzhou.github.io/blob/master/buildlog.txt),

and here is the [CMakeCache.txt](https://github.com/orionzhou/orionzhou.github.io/blob/master/CMakeCache.txt)

I think it's linking against the recent boost (1.69.0):

> (base) zhoux379@ln0003:build $ grep BOOST_LIB_VERSION /home/springer/zhoux379/software/miniconda3/include/boost/version.hpp
> //  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
> #define BOOST_LIB_VERSION "1_69"

Thanks so much!

**Comment by bschiffthaler** [comment]
Alright, seems boost 1.69 causes issues.

I have successful builds with 1.66, 1.67 and 1.68 so downgrading boost to any of these versions should work with conda. It's a bit weird since the boost::po library is not supposed to have changed since 1.68 and that version still builds fine. I'll look into that in more detail, but for now:

```bash
conda create -n seidr -c bioconda -c conda-forge htslib boost=1.67.0 cmake gxx_linux-64 gcc_linux-64 gfortran_linux-64 gsl glpk armadillo openmpi tclap
conda activate seidr
CMAKE_PREFIX_PATH=$CONDA_PREFIX cmake -DCMAKE_BUILD_TYPE=Release ..
make 
```

**Comment by orionzhou** [comment]
It passed compiling!  Thanks a lot for troubleshooting!  I can't wait to try the various utilities!
